apiVersion: v1
kind: Pod
metadata:
 name: pod-java-web-application
 namespace: login
 labels:
   app: java-web-application
spec:
  containers:
  - name: java-web-application
    image: naveenkuamr/m-w-application:tag
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-web-application
  namespace: login
spec:
  type: NodePort
  selector:
    app: java-web-application
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 32767
